name: 'Test'

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

permissions:
  contents: read # for actions/checkout to fetch code
  security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
  actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

jobs:
  checkov:
    name: 'Test'
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4
      
      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@v12
        with:
          # This will add a CLI output to the console
          output_format: cli
          output_file_path: console
          quiet: true